# Week2授業前課題3 行列積のスクラッチ

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

## 【問題1】行列積を手計算する

In [ ]:
#    |-1  2  3|      | 0  2  1|
#A = | 4 -5  6|  B = | 0  2 -8|
#    | 7  8 -9|      | 2  9 -1|
#
#      |(-1)*0+2*0+3*2 (-1)*2+2*2+3*9 (-1)*1+2*(-8)+3*(-1)|
#A・B =|4*0+(-5)*0+6*2 4*2+(-5)*2+6*9 4*1+(-5)*(-8)+6*(-1)|
#      |7*0+8*0+(-9)*2 7*2+8*2+(-9)*9 7*1+8*(-8)+(-9)*(-1)|
#   
#      |  6  29 -20|
#     =| 12  52  38|
#      |-18 -51 -48|
#
#


## 【問題2】NumPyの関数による計算

In [8]:
import numpy as np
# np.matmul()の場合
ans_matmul = np.matmul(a_ndarray, b_ndarray)
ans_matmul

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [7]:
# np.dot()の場合
ans_dot = np.dot(a_ndarray, b_ndarray)
ans_dot

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [6]:
# @演算子の場合
ans_atmark = a_ndarray @ b_ndarray
ans_atmark

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【問題3】ある要素の計算を実装

In [10]:
# 0列0行目の要素を算出
sum_data11 = 0
for k in range(3):
    sum_data11 += a_ndarray[0][k]*b_ndarray[k][0]
sum_data11

6

## 【問題4】行列積を行う関数の作成

In [22]:
def matrix_product(a_ndarray, b_ndarray):
    # 求める変数を0で初期化
    c_ndarray = np.zeros((3,3))
    sum_data = 0
    for i in range(3):
        for j in range(3):
            sum_data = 0
            for k in range(3):
                # 要素毎に合計
                sum_data += a_ndarray[i][k] * b_ndarray[k][j]
            c_ndarray[i][j] =sum_data
            
    return c_ndarray
    



In [23]:
c_ndarray = matrix_product(a_ndarray, b_ndarray)
c_ndarray

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

### 4.行列積が定義されない組み合わせの行列

In [24]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [28]:
# 行数と列数が一致していないのでエラーとなります。
matrix_product(d_ndarray_, e_ndarray)

IndexError: index 2 is out of bounds for axis 0 with size 2

## 【問題5】計算が定義されない入力を判定する

In [68]:
# shepe判定追加版
def matrix_product_custom(a_ndarray, b_ndarray):
    print("第１引数の行数 = {}".format(a_ndarray.shape[0]))
    print("第２引数の列数 = {}".format(b_ndarray.shape[1]))
    
    if a_ndarray.shape[0] != b_ndarray.shape[1]:
        print("第1引数の行数と、第2引数の列数が異なるため、計算できません")
        return
    
    print("\n第１引数 = \n{}".format(a_ndarray))
    print("\n第２引数 = \n{}".format(b_ndarray))
    # 求める変数を0で初期化
    c_ndarray = np.zeros((3,3))
    sum_data = 0
    for i in range(3):
        for j in range(3):
            sum_data = 0
            for k in range(3):
                # 要素毎に合計
                sum_data += a_ndarray[i][k] * b_ndarray[k][j]
            c_ndarray[i][j] =sum_data
            
    return c_ndarray

In [69]:
matrix_product_custom(d_ndarray_, e_ndarray)

第１引数の行数 = 2
第２引数の列数 = 3
第1引数の行数と、第2引数の列数が異なるため、計算できません


In [70]:
matrix_product_custom(a_ndarray, b_ndarray)

第１引数の行数 = 3
第２引数の列数 = 3

第１引数 = 
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]

第２引数 = 
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## 【問題6】転置

In [71]:
# np.transpose()を使用
matrix_product_custom(a_ndarray, np.transpose(b_ndarray))

第１引数の行数 = 3
第２引数の列数 = 3

第１引数 = 
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]

第２引数 = 
[[ 0  0  2]
 [ 2  2  9]
 [ 1 -8 -1]]


array([[  7., -20.,  13.],
       [ -4., -58., -43.],
       [  7.,  88.,  95.]])

In [72]:
# .Tアトリビュートを使用
matrix_product_custom(a_ndarray, b_ndarray.T)

第１引数の行数 = 3
第２引数の列数 = 3

第１引数 = 
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]

第２引数 = 
[[ 0  0  2]
 [ 2  2  9]
 [ 1 -8 -1]]


array([[  7., -20.,  13.],
       [ -4., -58., -43.],
       [  7.,  88.,  95.]])