# Week2授業前課題3 行列積のスクラッチ

## 1.このテキストについて
<u>テキストの目的</u>  
・数式演算ライブラリのNumPyに慣れる
・行列演算に慣れる 

<u>どのように学ぶか</u>  
行列積の計算を手計算で行った後、スクラッチ実装することで理解を深めていきます。

## 2.行列積
以下のような行列A、Bを考えます。

$
% <![CDATA[
A = \left[
\begin{array}{ccc}
  -1 & 2 & 3 \\
  4 & -5 & 6 \\
  7 & 8 & -9
\end{array}
\right],
B = \left[
\begin{array}{ccc}
  0 & 2 & 1 \\
  0 & 2 & -8 \\
  2 & 9 & -1
\end{array}
\right] %]]>
$


NumPyで表すと次のようになります。  
```python
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
```

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

## 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。


計算過程もマークダウンテキストを用いて説明してください

```python
    |-1  2  3|      | 0  2  1|
A = | 4 -5  6|  B = | 0  2 -8|
    | 7  8 -9|      | 2  9 -1|

      |(-1)*0+2*0+3*2 (-1)*2+2*2+3*9 (-1)*1+2*(-8)+3*(-1)|
A・B =|4*0+(-5)*0+6*2 4*2+(-5)*2+6*9 4*1+(-5)*(-8)+6*(-1)|
      |7*0+8*0+(-9)*2 7*2+8*2+(-9)*9 7*1+8*(-8)+(-9)*(-1)|
   
      |  6  29 -20|
     =| 12  52  38|
      |-18 -51 -48|


```

## 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください。


[numpy.matmul — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul)


[numpy.dot — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)

《3種類の違い》


np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。


今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。


>If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

＜np.matmul()＞

In [8]:
import numpy as np
# np.matmul()の場合
ans_matmul = np.matmul(a_ndarray, b_ndarray)
ans_matmul

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

＜np.dot()＞

In [7]:
# np.dot()の場合
ans_dot = np.dot(a_ndarray, b_ndarray)
ans_dot

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

＜@演算子＞

In [6]:
# @演算子の場合
ans_atmark = a_ndarray @ b_ndarray
ans_atmark

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 3.行列積のスクラッチ実装
np.matmul()やnp.dot()、または@演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。

## 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。


1.行列Aの(0,0)の要素 $a_{0,0}$ と行列Bの(0,0)の要素 $b_{0,0}$ を掛け合わせる  
2.行列Aの(0,1)の要素 $a_{0,1}$ と行列Bの(1,0)の要素 $b_{1,0}$ を掛け合わせる  
3.行列Aの(0,2)の要素 $a_{0,2}$ と行列Bの(2,0)の要素 $b_{2,0}$ を掛け合わせる  
4.それらの値を全て足し合わせる  

数式で表すと

$
\sum^{2}_{k=0}a_{0,k}b_{k,0}
$

です。


この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [10]:
# 0列0行目の要素を算出
sum_data11 = 0
for k in range(3):
    sum_data11 += a_ndarray[0][k]*b_ndarray[k][0]
sum_data11

6

## 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である $3×3$ の行列Cの各要素 $c_{i,j}$ は数式で表すと次のようになります。

$
c_{i,j} = \sum^{2}_{k=0}a_{i,k}b_{k,j}
$

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス $i$ や $j$ を1増やすと、次の行や列に移ることができます。
<img src="https://t.gyazo.com/teams/diveintocode/129123df5242c9e768513f5e8b5ef24f.png" style="background-color:#FFFFFF;">

In [22]:
def matrix_product(a_ndarray, b_ndarray):
    # 求める変数を0で初期化
    c_ndarray = np.zeros((3,3))
    sum_data = 0
    for i in range(3):
        for j in range(3):
            sum_data = 0
            for k in range(3):
                # 要素毎に合計
                sum_data += a_ndarray[i][k] * b_ndarray[k][j]
            c_ndarray[i][j] =sum_data
            
    return c_ndarray
    



In [23]:
c_ndarray = matrix_product(a_ndarray, b_ndarray)
c_ndarray

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## 4.行列積が定義されない組み合わせの行列

In [24]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

In [28]:
# 行数と列数が一致していないのでエラーとなります。
matrix_product(d_ndarray_, e_ndarray)

IndexError: index 2 is out of bounds for axis 0 with size 2

## 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [68]:
# shepe判定追加版
def matrix_product_custom(a_ndarray, b_ndarray):
    print("第１引数の行数 = {}".format(a_ndarray.shape[0]))
    print("第２引数の列数 = {}".format(b_ndarray.shape[1]))
    
    if a_ndarray.shape[0] != b_ndarray.shape[1]:
        print("第1引数の行数と、第2引数の列数が異なるため、計算できません")
        return
    
    print("\n第１引数 = \n{}".format(a_ndarray))
    print("\n第２引数 = \n{}".format(b_ndarray))
    # 求める変数を0で初期化
    c_ndarray = np.zeros((3,3))
    sum_data = 0
    for i in range(3):
        for j in range(3):
            sum_data = 0
            for k in range(3):
                # 要素毎に合計
                sum_data += a_ndarray[i][k] * b_ndarray[k][j]
            c_ndarray[i][j] =sum_data
            
    return c_ndarray

In [69]:
matrix_product_custom(d_ndarray_, e_ndarray)

第１引数の行数 = 2
第２引数の列数 = 3
第1引数の行数と、第2引数の列数が異なるため、計算できません


In [70]:
matrix_product_custom(a_ndarray, b_ndarray)

第１引数の行数 = 3
第２引数の列数 = 3

第１引数 = 
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]

第２引数 = 
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。


np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。


[numpy.transpose — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html)


[numpy.ndarray.T — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html)

In [71]:
# np.transpose()を使用
matrix_product_custom(a_ndarray, np.transpose(b_ndarray))

第１引数の行数 = 3
第２引数の列数 = 3

第１引数 = 
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]

第２引数 = 
[[ 0  0  2]
 [ 2  2  9]
 [ 1 -8 -1]]


array([[  7., -20.,  13.],
       [ -4., -58., -43.],
       [  7.,  88.,  95.]])

In [72]:
# .Tアトリビュートを使用
matrix_product_custom(a_ndarray, b_ndarray.T)

第１引数の行数 = 3
第２引数の列数 = 3

第１引数 = 
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]

第２引数 = 
[[ 0  0  2]
 [ 2  2  9]
 [ 1 -8 -1]]


array([[  7., -20.,  13.],
       [ -4., -58., -43.],
       [  7.,  88.,  95.]])