# Week4授業前課題3 オブジェクト指向の活用

In [13]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)
print("X_std = \n{}".format(X_std))

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
X_std = 
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [4]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [2]:
scaler0 = StandardScaler()
scaler1 = StandardScaler()
scaler2 = StandardScaler()

## 【問題1】これまで利用してきたクラスの列挙

pandas:  
    DataFrameクラス  
    
matplotlib：  
    figureクラス、subplotsクラス  
    
scikit-learn：  
preprocessing.StandardScaler()、neighbors.KNeighborsClassifier()、  
metrics.classification_report()、 metrics.confusion_matrix()  
linear_model.LogisticRegression()、svm.SVC()、  
tree.DecisionTreeClassifier()、ensemble.RandomForestClassifier()  
linear_model.LinearRegression()、svm.SVR()、tree.DecisionTreeRegressor()、ensemble.RandomForestRegressor()

In [3]:
print("平均 : {}".format(scaler.mean_)) # 平均 : [4.86 3.31 1.45 0.22]
print("分散 : {}".format(scaler.var_)) # 分散 : [0.0764 0.0849 0.0105 0.0056]

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


## 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

メソッド：  
load_iris()、value_counts()、np.array()、train_test_split()、type()、fit()、f1_score()、confusion_matrix()、.describe()、.corr()

インスタンス変数：  
shape、math.pi、iris_data.target、iris_data.target_names、iris_data.data、mean_、var_

## 【問題3】標準化クラスをスクラッチで作成

標準化  
x' = (x - μ)/σ  
μ：平均  
σ：標準偏差 ⇒ np.std()


In [74]:
import numpy as np
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X, axis = 0)
        self.var_ = np.var(X, axis = 0)

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
            
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """

        # 標準偏差
        X_std = np.std(X, axis = 0)
        
        X_scaled = (X - self.mean_)/X_std
        return X_scaled

In [75]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print("X_std = \n{}".format(X_std))

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
X_std = 
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


## 【問題4】 四則演算を行うクラスの作成

In [76]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        # int か float のみ処理する
        if type(value) is int or type(value) is float:
            self.value = value
            print("初期値{}が設定されました".format(self.value))
        else:
            print("数値を指定してください！ 入力データ:{}".format(value))   

        
    # 足し算
    def add(self, value1):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value1
        
    # 引き算
    def minus(self, value2):
        """
        受け取った引数をself.valueから引く
        """
        self.value -= value2
        
    # 掛け算
    def multiplication(self, value3):
        """
        受け取った引数をself.valueに掛ける
        """
        self.value *= value3
        
    # 割り算
    def division(self, value4):
        """
        受け取った引数をself.valueから割る
        """
        self.value /= value4
        

In [77]:
try:
    test_list = [1,2, 3, 4]
    example = ExampleClass(5)
    print("value : {}".format(example.value))

    print("\n7を足します")
    example.add(7)
    print("value : {}".format(example.value))

    print("\n2を引きます")
    example.minus(2)
    print("value : {}".format(example.value))

    print("\n3を掛けます")
    example.multiplication(3)
    print("value : {}".format(example.value))

    print("\n5で割ります")
    example.division(5)
    print("value : {}".format(example.value))
    
except AttributeError:
    print("エラーが発生しました")

初期値5が設定されました
value : 5

7を足します
value : 12

2を引きます
value : 10

3を掛けます
value : 30

5で割ります
value : 6.0


In [79]:
# エラー処理確認
try:
    test_list = [1,2, 3, 4]
    example = ExampleClass(test_list)
    print("value : {}".format(example.value))
    
except AttributeError:
    print("エラーが発生しました")
    
try:
    example = ExampleClass("5")
    print("value : {}".format(example.value))
    
except AttributeError:
    print("エラーが発生しました")
    

数値を指定してください！ 入力データ:[1, 2, 3, 4]
エラーが発生しました
数値を指定してください！ 入力データ:5
エラーが発生しました
